[send]
command:/usr/local/opnsense/scripts/netreport/netreport.py send
parameters:%s
type:script_output
message:Sending network report %s

[preview]
command:/usr/local/opnsense/scripts/netreport/netreport.py preview
parameters:%s
type:script_output
message:Rendering network report preview %s

[testmail]
command:/usr/local/opnsense/scripts/netreport/netreport.py testmail
parameters:
type:script_output
message:Sending network report test message

[history]
command:/usr/local/opnsense/scripts/netreport/netreport.py history
parameters:
type:script_output
message:Listing network report history

[view]
command:/usr/local/opnsense/scripts/netreport/netreport.py view
parameters:%s
type:script_output
message:Showing archived network report %s
